sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: GnlwzacpHWAL7zW7yD80+6z3ZKO+N/oS+NAcSYRJZitC2rVEbgSkyDtY0DIBACVd4yn9b7e9TWuGBVC1uaLf/CJvEL47hoacvDahAdC0XyG+uAee9BTHLPzTYDPexrqsdaYPHCugulKNrEnam16JU6dkvAMp9YfWZYTuJQMNQrdQK2+oUMWAC8YcmjxpF/M1UIe9S3MChAWi4JkKvGM3A6my+OcJ45K7MvCUwvCV6RwTDaSO7dv57kVD4+4e4yqaHJn6hXQ8b4oETXGF+rJqK1tZu84RDQAsf9Zcic9wfUcLgqDw/jSmSXKFybxT/DCAL4OCL/PJMGMbB0kZJhxsgsP6Gd3iC2NhlQU99jdMpAkBBYdczZ/dGXtUNiX9JBaNzqg4fre6Zvf1xg1eQm0l5WIijLONVptV3EqVXaFUZQdMmeDxKSKqPG0snHuosMWO6GmRDxYNCsI73k8f7uFLTXbShgXQ1doWHypAIVw73CXndmgPu9SpdR4zK5LEW/BV7KmoLQ8deSlCYqQZMy5GSwty3AVBcmCoD8FacWlClxSMnD8H4YMKxqZOx4qr2pYW5+rPkZ8q8Uk1+ArbW2suGe8fJnc7Bt7qJZAe1yWmrxZZ7O5swBNESNycLQ3UDpcm20ouyLPuryc3E2FLybEevdzrsyDbRhoun6sZtEWwAyw=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: VQPf5qdXeAtsOuSQT3ECn+orrNgFWZvkIbBOrLiR1ZdJNL55xmynfHYa3k1VYuy0wd4al1LejRm1lIw/6r2epfJYbIPPQJNM4iUeVxCArCbqoBDwgO+AoAc2PSCotu10wPiDSr32IQ09/Oy4poanNH2B13sm3jCcvNj9GxwqDuQgBipXqSLTS+xAhJYXdmgXbNE6s4loGp8bSN54tgqnibg6mE/nXqlthYn5+NBbVMK3A2m3b5iIGwe+tbv+4gf6BwwGMBd0Oku7JPjarzqUAKPX4E4yWVuXTLeUNCDPikVBHWbA70rAyKPcz/kN7EsFoftLUb6q1gXxxmOACFxM38epktz2kGvtTDKveqh8f68eiscJ4W3XzlQsgu5fiZMdly/QIIBkjFdXLupi0rGZ6vw87XjCbk8M1YtRgWo397u9hQyBEu2sZvXOpVs4lGK1apPrSjvN7w3alp9NSAp2oR6T97P+AhOlQ5fwUIyEuOThK0qyr8h+haz5WLdx6Vy17jcACYon9oKhp+2XFUwfoglvPf/AxRcVnHx4ae9rpvxnZJl8kT3bRpRsQGxn/nyLo3FkReyA3jNaJ8y+zKy6CTKenB+jA7hfVoYhHnJZU/w4PfkJ0ONOPVMNatKegrJEEIXmjsB987q5zw2wVuRLrf/N/EveMBxds4fn2zfYknk=
